classdef key_def_template < handle & key_def
methods
    function obj=key_def_template();
        obj@key_set();

        obj.n('\n')  =''
        obj.n('\]')  =''

        obj.n('\B')  =''
        obj.n('\t')  =''
        obj.n('\tS') =''
        obj.n('\s')  =''
        obj.n('\sS') =''

        obj.n('a')   =''
        obj.n('b')   =''
        obj.n('c')   =''
        obj.n('d')   =''
        obj.n('e')   =''
        obj.n('f')   =''
        obj.n('g')   =''
        obj.n('h')   =''
        obj.n('i')   =''
        obj.n('j')   =''
        obj.n('k')   =''
        obj.n('l')   =''
        obj.n('m')   =''
        %n('n')   =''
        obj.n('o')   =''
        obj.n('p')   =''
        obj.n('q')   =''
        obj.n('r')   =''
        obj.n('s')   =''
        obj.n('t')   =''
        obj.n('u')   =''
        obj.n('v')   =''
        obj.n('w')   =''
        obj.n('x')   =''
        obj.n('y')   =''
        obj.n('z')   =''

        obj.n('A')   =''
        obj.n('B')   =''
        obj.n('C')   =''
        obj.n('D')   =''
        obj.n('E')   =''
        obj.n('F')   =''
        obj.n('G')   =''
        obj.n('H')   =''
        obj.n('I')   =''
        obj.n('J')   =''
        obj.n('K')   =''
        obj.n('L')   =''
        obj.n('M')   =''
        obj.n('N')   =''
        obj.n('O')   =''
        obj.n('P')   =''
        obj.n('Q')   =''
        obj.n('R')   =''
        obj.n('S')   =''
        obj.n('T')   =''
        obj.n('U')   =''
        obj.n('V')   =''
        obj.n('W')   =''
        obj.n('X')   =''
        obj.n('Y')   =''
        obj.n('Z')   =''

        obj.n('1')   =''
        obj.n('2')   =''
        obj.n('3')   =''
        obj.n('4')   =''
        obj.n('5')   =''
        obj.n('6')   =''
        obj.n('7')   =''
        obj.n('9')   =''
        obj.n('0')   =''

        obj.n('!')   =''
        obj.n('?')   =''
        obj.n('@')   =''
        obj.n('#')   =''
        obj.n('$')   =''
        obj.n('%')   =''
        obj.n('^')   =''
        obj.n('*')   =''
        obj.n('(')   =''
        obj.n(')')   =''
        obj.n('[')   =''
        obj.n(']')   =''
        obj.n('{')   =''
        obj.n('}')   =''
        obj.n('+')   =''
        obj.n('-')   =''
        obj.n('=')   =''
        obj.n(':')   =''
        obj.n('.')   =''
        obj.n(',')   =''
        obj.n('\')   =''

        obj.n('\R')  =''
        obj.n('\L')  =''
        obj.n('\U')  =''
        obj.n('\D')  =''

    end
end
end
